### ISSUE TITLE
feat(azure-db): we can use the raw base64 version of the PG env vars

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/docker#150]
\from @gary-van-woerkens 
We do not need to decode or parse the PG env var for `@` if we use the base64 version ;)

**Comment by revolunet** [comment]
to be defined in the WIP [PG docs](https://hackmd.io/zV266WIYSZ6PuRfDb2hjCg?both) ?

**Comment by revolunet** [comment]
fixed with sealed-secrets
