### ISSUE TITLE
feat(nginx for spa): déprécier 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/docker#824]
L'utilisation de variables d'environnements est désormais supportée par l'image docker officielle: https://hub.docker.com/_/nginx/
> Using environment variables in nginx configuration (new in 1.19)

Peut-être l'occasion de déprécier la fonctionnalité de remplacement automatique de cette image (en pointant vers la documentation officielle): https://github.com/SocialGouv/docker/tree/master/nginx4spa#envsubst-on-startup

**Comment by revolunet** [comment]
Vous utilisez du routing côté client type SPA dans domifa ?

**Comment by revolunet** [comment]
en fait... les variables d'environment ne sont pas `envsubst` _que_ dans la conf nginx mais aussi dans les fichier statiques, ce que ne propose pas nginx par défaut
